#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright (C) 2013, John Hampton <pacopablo@pacopablo.com>
# All rights reserved
#
#
# Author: John Hampton <pacopablo@pacopablo.com>

# Standard Library Imports
import sys
import imaplib
import getpass

# Third Party Imports
from gdata.apps.migration import service

VERSION='0.1.0'


if __init__ == '__main__':
    rc = 0
    sys.exit(rc)
